config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    get 'relationships/followings'
    get 'relationships/followers'
  end
  # ユーザー用
  # URL /users/sign_in
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  # ゲスト用
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  # 管理者用
  # URL /admin/sign_in
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  root to: 'public/homes#top'
  get 'about' => 'public/homes#about'
  get 'books/search', to: "public/books#search"

  resources :tags do
    get 'reviews', to: 'public/reviews#search'
  end

  namespace :admin do
    root to: "users#index"
    resources :users
    resources :reviews
  end

  namespace :public do
    resources :users do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
  end
    resources :books do
      resources :reviews do
        resource :favorites, only: [:create, :destroy]
      end
    end
end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,authentication_keys: [:name]

  has_many :reviews, dependent: :destroy
  has_many :books
  has_many :favorites, dependent: :destroy
  # フォローをした、されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  # 一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

    # フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com',name:"guest") do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  def index
    @users = User.all.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = 'ユーザーを削除しました。'
    redirect_to request.referer
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to public_books_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/index.html.erb
<!--ユーザー一覧（名前とemailが確認できる）-->
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="h3 pb-2 mb-4 mt-4 text-dark border-bottom border-dark">
       <p class="text-center"><strong>ユーザー一覧</strong></p>
      </div>
      <table class="table table-borderless">
        <thead>
          <tr>
            <th scope="col">ユーザー名</th>
            <th scope="col">Eメール</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <% @users.each do |user| %>
        <tbody>
          <tr>
            <td><%= link_to user.name,admin_user_path(user.id) %></td>
            <td><%= user.email %></td>
            <td><%= link_to "削除する",admin_user_path(user.id), class: "destroy-user", method: :delete, class:"btn btn-danger", "data-confirm" => "本当に退会しますか？" %></td>
          </tr>
        </tbody>
        <% end %>
        <%= paginate @users %>
      </table>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<!--１ユーザーのレビュー一覧(レビューを削除できる)-->
<div class="row">
  <div class="col-md-8 offset-md-2">
    <h3><strong><%= @user.name %>さんのレビュー投稿一覧</strong></h3>
    <br>
    <div class="card-deck">
      <% @reviews.each do |review| %>
      <div class="card">
        <div class="card-body">
          <div class="card-title">
            <h5><%= review.title %></h5>
          </div>
          <div class="card-text">
            <p><%= review.body %></p>
              <%= link_to "削除する", public_book_review_path(review.book, review), method: :delete,"data-confirm" => "本当に削除しますか？",class:"btn btn-danger" %>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>
<br>