config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    get 'relationships/followings'
    get 'relationships/followers'
  end
  # ユーザー用
  # URL /users/sign_in
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  # ゲスト用
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  # 管理者用
  # URL /admin/sign_in
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  root to: 'public/homes#top'
  get 'about' => 'public/homes#about'
  get 'books/search', to: "public/books#search"

  resources :tags do
    get 'reviews', to: 'public/reviews#search'
  end

  namespace :admin do
    root to: "users#index"
    resources :users
    resources :reviews
  end

  namespace :public do
    resources :users do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
  end
    resources :books do
      resources :reviews do
        resource :favorites, only: [:create, :destroy]
      end
    end
end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  # bookのプライマリキーをisbnにする
  self.primary_key = "isbn"
  has_many :reviews, dependent: :destroy
end

app/models/book_tag.rb
class BookTag < ApplicationRecord
  belongs_to :review
  belongs_to :tag

  validates :review_id, presence: true
  validates :tag_id, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  # class_name: "User"でUserモデルを参照
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user

  # ブックのプライマリキーをisbnにする
  belongs_to :book, primary_key: "isbn"
  # タグ検索
  has_many :book_tags, dependent: :destroy
  has_many :tags, through: :book_tags# through(Review.tagsとすればReviewに紐付けられたTagの取得が可能になるオプション)
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true
  validates :star, presence: true
    # ソート機能
    scope :latest, -> {order(created_at: :desc)}
    scope :old, -> {order(created_at: :asc)}
    scope :star_count, -> {order(star: :desc)}

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
# createアクションで記述したsave_tagインスタンスメソッドの中身を定義する
  def save_tag(sent_tags)
    # @reviewに紐付いているタグが存在する場合全てのデータを取得する

    current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
    # 取得した@reviewに存在するタグから、送信されてきたタグを除いたタグ
    old_tags = current_tags - sent_tags
    # 送信されてきたタグから、現在存在するタグを除いたタグ
    new_tags = sent_tags - current_tags

    old_tags.each do |old|
      # 古いタグを削除
     self.tags.delete Tag.find_by(tag_name: old)
    end

    new_tags.each do |new|
      # 新しいタグを保存
     new_review_tag = Tag.find_or_create_by(tag_name: new)
     self.tags << new_review_tag
    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :book_tags, dependent: :destroy, foreign_key: 'tag_id'
  has_many :reviews, through: :book_tags
  
  

  # def name_tag(str)
  #   require 'nkf'
  #   str = "アイウエオＡＢＣ０１２"
  #   # nkfライブラリを使用して変換を実行
  #   p NKF.nkf('-w -Z4', str)
  # end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,authentication_keys: [:name]

  has_many :reviews, dependent: :destroy
  has_many :books
  has_many :favorites, dependent: :destroy
  # フォローをした、されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  # 一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

    # フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com',name:"guest") do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  
  def top
  end
  
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
  
  def index
  end
  
  def show
  end
  
  def destroy
  end
  
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params,if: :devise_controller?

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email])
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  def index
    @users = User.all.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = 'ユーザーを削除しました。'
    redirect_to request.referer
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_admin!, if: :admin_url
  before_action :authenticate_user!, if: :public_url

  def admin_url
    request.fullpath.include?("/admin")
  end

  def public_url
    request.path.include?("/public") && !admin_signed_in?
  end


    # ログイン後のリダイレクト先
  def after_sign_in_path_for(resource_or_scope)
    if resource.is_a?(Admin)
      admin_root_path
    else
      public_books_path
    end
  end

  # ログアウト後のリダイレクト先
  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :admin
      new_admin_session_path
    else
      root_path
    end
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to public_books_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container-fluid pt-2 pb-2 bg-dark'>
  	<div class='row'>
    	<div class='mx-auto'>
    		<p class="text-light">©Book Review x 楽天api</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="shadow-sm">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container-fluid">
      <a class="navbar-brand" href="/"><h2><strong>Book Review</strong></h2></a>
      <% if current_user.present? %>
        <p class="text-light">こんにちは、<%= current_user.name %>さん！</p>
      <% else %>
        <p class="text-light">こんにちは、ゲストさん！</p>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                    aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
            <!--ゲストログインあとで修正する-->
        <% if user_signed_in? %>
         <li class="nav-item">
           <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-white' %>
         </li>
         <li class="nav-item">
           <%= link_to 'レビューブック一覧', public_books_path, class: 'nav-link text-white' %>
         </li>
         <li class="nav-item">
           <%= link_to 'マイページ', public_user_path(current_user.id), class: 'nav-link text-white' %>
         </li>
          <li class="nav-item">
           <%= link_to 'ブックマーク一覧', public_users_path(current_user.id), class: 'nav-link text-white' %>
         </li>
         <li class="nav-item">
          <!--検索フォーム-->
          <%= render 'public/books/form', title: @title %>
          </li>
        <% elsif admin_signed_in? %>
         <li class="nav-item">
           <%= link_to "管理者ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-white' %>
         </li>
          <li class="nav-item">
            <%= link_to 'ユーザー一覧', admin_root_path, class: 'nav-link text-white' %>
          </li>
        <% else %>
          <li class="nav-item">
           <%= link_to 'アバウト', about_path, class: 'nav-link text-white' %>
          </li>
         <li class="nav-item">
           <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-white' %>
         </li>
         <li class="nav-item">
           <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-white' %>
         </li>
          <li class="nav-item">
            <%= link_to '管理者ログイン', new_admin_session_path, class: 'nav-link text-white' %>
          </li>
        <% end %>
        </ul>
      </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookReview</title>
    <script src="https://kit.fontawesome.com/e35a94ee4b.js" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="padding-top:4.5rem;">
    <%= render 'layouts/header' %>
    <!--アラート-->
    <% if flash[:notice ] %>
      <div class="alert alert-primary">
        <%= notice %><button type="button" class="close" data-dismiss="alert">&times;</button>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-danger">
        <%= alert %><button type="button" class="close" data-dismiss="alert">&times;</button>
      </div>
    <% end %>
    <main>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>